﻿model: "yolo11s.pt"  # Using smaller v11s model for efficiency
epochs: 200
batch_size: 8
img_size: 1080
data_yaml: "DELIVERY/PROBLEM1/src/data/dataset.yaml"
test_images_dir: "DELIVERY/PROBLEM1/src/data/images/test"
experiment_name: "A star hackaton"
